APP:
  DEMO: false
  MODE: 'challenge' # options: 'standard' | 'challenge'

API:
  # define a global endpoint
  # API will be as follows
  # GLOBAL/dataset
  # GLOBAL/dataset/:id_dataset
  # GLOBAL/dataset/:id_dataset/table
  # GLOBAL/dataset/:id_dataset/table/:id_table
  # GLOBAL/getAnnotations
  # GLOBAL/getCEA
  # GLOBAL/getCPA
  # GLOBAL/getCTA
  GLOBAL: "http://149.132.178.111:3000"

  # override endpoint for each API
  GET_DATASET: "http://149.132.178.111:3000/dataset"
  GET_DATASET_INFO: "http://149.132.178.111:3000/dataset/:id_dataset"
  GET_TABLES_BY_DATASET: "http://149.132.178.111:3000/dataset/:id_dataset/table"
  GET_TABLE: "http://149.132.178.111:3000/dataset/:id_dataset/table/:id_table"
  GET_ANNOTATIONS: null
  GET_CEA: null
  GET_CPA: null
  GET_CTA: null

  # multiple endpoints
  PROCESS_START:
    - api: null
      name: "Endpoint 1"
    - api: null
      name: "Endpoint 2"


SETTINGS:
#  GROUP_BY_DATASET: false
  GLOBAL:
    # set tables' header index (usually -1 or 0) to display annotations properly
    TABLES_HEADERS_INDEX: -1

  # customize colors for annotations
  SCORE_DISPLAY:
    LOW_SCORE:
      HIGHLIGHT: false
      THRESHOLD: 0.4
      COLOR: "#f5d4d4"
    HIGH_SCORE:
      HIGHLIGHT: false
      THRESHOLD: 0.8
      COLOR: "#dfead2"
    OTHER_SCORE:
      HIGHLIGHT: false
      COLOR: "#e8e8e8"

  TABLE_PAGINATION:
    ROWS_COUNT: 200

