API:
  # Define a global base url
  GLOBAL: "${REACT_APP_GLOBAL_URL}"

  # App endpoints
  ENDPOINTS:
    GET_SERVICES_CONFIG:
      # endpoint path
      path: '${REACT_APP_BACKEND_URL}/config'
      # the 'path' will be appended to the global endpoint if true
      useGlobal: false
    # Get all datasets (mandatory)
    GET_DATASET:
      # endpoint path
      path: '${REACT_APP_BACKEND_URL}/dataset'
      # the 'path' will be appended to the global endpoint if true
      useGlobal: false

    # Get details of a dataset (optional)
    GET_DATASET_INFO:
      path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId'
      useGlobal: false

    # Get all tables of a dataset (mandatory)
    GET_TABLES_BY_DATASET:
      path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId/table'
      useGlobal: false

    # Get a table (mandatory)
    GET_TABLE:
      path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId/table/:tableId'
      useGlobal: false

    # Delete a dataset (optional)
    DELETE_DATASET:
      path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId'
      useGlobal: false
    
    # Delete a table (optional)
    DELETE_TABLE:
      path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId/:tableId'
      useGlobal: false

    # Global search of datasets and tables (optional)
    GLOBAL_SEARCH:
      - path: '${REACT_APP_BACKEND_URL}/dataset/search?query=:query'
        useGlobal: false

    # Upload a dataset (zip / rar) (optional)
    UPLOAD_DATASET:
      - path: '${REACT_APP_BACKEND_URL}/dataset'
        useGlobal: false

    # Save changes made to a table (optional)
    SAVE:
      - path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId/table/:tableId'
        useGlobal: false

    # Multiple endpoints for multiple annotation processes (optional)
    PROCESS_START:
      - path: '/path/process/start1'
        name: "Endpoint 1"
        useGlobal: true
      - path: '/path/process/start2'
        name: "Endpoint 2"
        useGlobal: true

    # Export a table in a specified format (optional)
    EXPORT:
      - path: '${REACT_APP_BACKEND_URL}/dataset/:datasetId/table/:tableId/export?format=w3c'
        name: 'W3C'
        useGlobal: false
