name: Workflow to build a docker image and push it to GitHub and DockerHub registries
on: 
  push:
    branches:
      - dev
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone frontend repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          path: frontend/

      - name: Cache frontend dependencies
        uses: actions/cache@v2 # https://github.com/actions/cache
        with:
          path: ~/frontend/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      
      - name: Build frontend app
        run: cd frontend && npm ci && npm run build && cd ../

      - name: Clone backend repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          repository: I2Tunimib/I2T-backend
          path: backend/
      
      - name: Cache backend dependencies
        uses: actions/cache@v2
        with:
          path: ~/backend/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      
      - name: Move frontend build folder inside backend folder
        run: mkdir backend/build && mv frontend/build/* backend/build/ && cd backend/build && ls

      - name: Login to Docker Hub
        uses: docker/login-action@v1 # https://github.com/docker/login-action
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Login to GithHub Container
        uses: docker/login-action@v1 # https://github.com/docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to DockerHub and GitHub registry
        run: cd backend && docker-compose build && docker-compose push
